# Generated by Django 3.0.2 on 2024-10-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PYPRmanage', '0002_auto_20241011_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_orders',
            name='PowerUnit',
            field=models.CharField(choices=[('w', '瓦'), ('KW', '千瓦')], default='w', max_length=2),
        ),
        migrations.AddField(
            model_name='project_orders',
            name='unitType',
            field=models.CharField(choices=[('TA', '台'), ('TI', '条'), ('KU', '块'), ('GE', '个')], default='TA', max_length=2),
        ),
    ]
